[package]
name = "__package_name"
version = "0.1.0"
authors = ["Jonathan Lorimer <jonathan_lorimer@mac.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[package.metadata.nix]
build = true
app = true
